### ISSUE TITLE
LC0003 and LC0005 on temporary tables as parameters in AL Language v11

### ISSUE THREAD

**Issue by NKarolak** [StefanMaron/vsc-lintercop#10]
This is an issue since AL Language v11 only, running on the latest linter version released today :

I have created a table with `TableType = Temporary`, name: `"My table name"`
Whenever such a temporary table is used as a var parameter (but without the "temporary" attribute), the following warnings are thrown:
- Do not use an Object ID for properties or variables declaration. Use `My table name" temporary` instead. ([LC0003](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0003))
- Wrong casing detected! Use `My table name" temporary` instead.  ([LC0005](https://github.com/StefanMaron/BusinessCentral.LinterCop/wiki/LC0005))

The "Use ..." instruction does not match the error message. And even if it did, the name is missing the leading `"`

**Comment by jwikman** [comment]
Hi again, @NKarolak!
I guess you get better response from community if reporting these issues at https://github.com/StefanMaron/BusinessCentral.LinterCop, since that repo handles all rules. This repo is for the VSCode extension, which is "only" used for easier distribution of the dll. :)


But anyways, I get the same warnings, but on all places I declared a record as temporary. And yes, the leading `"` is missing in the error.

**Comment by NKarolak** [comment]
>  since that repo handles all rules
Thanks Johannes, 
I didn't know that (anymore) 🙈
